/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Admin.View;
import Admin.Controller.TableStockRusak;
import Admin.Model.StockRusak;
import Admin.Controller.ProductCRUD;
import java.sql.SQLException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Ryan F
 */
public class ListStockRusak extends javax.swing.JFrame {
private int selectedId;
private ProductCRUD productDB;
private DefaultTableModel tableModel;
private ProductStockFrame ProductStock;

    public ListStockRusak() throws SQLException {
        initComponents();
        productDB = new ProductCRUD();
        tableModel = (DefaultTableModel) tabel_stockrusak.getModel();
        LoadTableStockRusak();
    }
    
    public ListStockRusak(String nama, String satuan) throws SQLException {
        initComponents();
        productDB = new ProductCRUD();
        tableModel = (DefaultTableModel) tabel_stockrusak.getModel();
        txtfield_product.setText(nama);
        txtfield_satuan.setText(satuan);
        LoadTableStockRusak();
    }
    
    public ListStockRusak(ProductStockFrame productStockFrame) throws SQLException {
    this.ProductStock = productStockFrame;
    initComponents();
    productDB = new ProductCRUD();
    LoadTableStockRusak();
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField4 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtfield_product = new javax.swing.JTextField();
        txtfield_satuan = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtfield_stock = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel_stockrusak = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        txtfield_stockrusak = new javax.swing.JTextField();
        btn_update = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jdate_tanggal = new com.toedter.calendar.JDateChooser();

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Stock :");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("LIST STOCK RUSAK");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Product  :");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Satuan :");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Stock :");

        tabel_stockrusak.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabel_stockrusak.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel_stockrusakMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabel_stockrusak);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Stock Rusak:");

        btn_update.setText("UPDATE");
        btn_update.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_updateMouseClicked(evt);
            }
        });
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Tanggal :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtfield_product, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(txtfield_stock, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(txtfield_satuan, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jdate_tanggal, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                                .addComponent(txtfield_stockrusak))
                            .addComponent(btn_update, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtfield_product, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtfield_satuan, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtfield_stock, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(jdate_tanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(txtfield_stockrusak, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(btn_update, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 
     private void LoadTableStockRusak() {
          if (tableModel == null) {
            JOptionPane.showMessageDialog(this, "Model tabel belum dimuat!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
          
        tableModel.setRowCount(0); // Kosongkan tabel
        tableModel.setColumnIdentifiers(new Object[]{"ID STOCK", "TANGGAL", "STOCK RUSAK"});

        try {
            for (StockRusak s : productDB.getStockRusak()) {
                tableModel.addRow(new Object[]{
                        s.getId_stock(),
                        s.getTanggal(),
                        s.getStock_rusak()
                });
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Gagal memuat data: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    
    
    private void tabel_stockrusakMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel_stockrusakMouseClicked
     int selectedRow = tabel_stockrusak.getSelectedRow();
        if (selectedRow != -1) {
            selectedId = Integer.parseInt(tabel_stockrusak.getValueAt(selectedRow, 0).toString()); // Get ID_STOCK
            Date tanggal = (Date) tabel_stockrusak.getValueAt(selectedRow, 1); // Get TANGGAL
            int stokRusak = Integer.parseInt(tabel_stockrusak.getValueAt(selectedRow, 2).toString()); // Get STOK_RUSAK

            // Populate the fields with the selected row's data
            jdate_tanggal.setDate(tanggal);
            txtfield_stockrusak.setText(String.valueOf(stokRusak));
        }
        
    }//GEN-LAST:event_tabel_stockrusakMouseClicked

    private void btn_updateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_updateMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_updateMouseClicked

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed
   if (selectedId == -1) {
            JOptionPane.showMessageDialog(this, "Pilih baris terlebih dahulu!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }
   
    if (jdate_tanggal.getDate() == null) {
            JOptionPane.showMessageDialog(this, "Tanggal belum dipilih!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }
    
     try {
            Date updatedTanggal = jdate_tanggal.getDate();
            int updatedStockRusak = Integer.parseInt(txtfield_stockrusak.getText());

            StockRusak stockToUpdate = new StockRusak();
            stockToUpdate.setId_Stock(selectedId);
            stockToUpdate.setTanggal(updatedTanggal);
            stockToUpdate.setStock_rusak(updatedStockRusak);
            
    int affectedRows = productDB.updateStokRusak(stockToUpdate);
            if (affectedRows > 0) {
                JOptionPane.showMessageDialog(this, "Data berhasil diperbarui!");
                LoadTableStockRusak(); // Refresh tabel
                
                // REFRESH TABEL DI ProductStockFrame
            if (ProductStock != null) {
                ProductStock.refreshData(); // <-- INI YANG DITAMBAHKAN
            }
                
            } else {
                JOptionPane.showMessageDialog(this, "Tidak ada perubahan.", "Peringatan", JOptionPane.WARNING_MESSAGE);
            }
     } catch (NumberFormatException | SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_updateActionPerformed

    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListStockRusak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListStockRusak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListStockRusak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListStockRusak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new ListStockRusak().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(ListStockRusak.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_update;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField4;
    private com.toedter.calendar.JDateChooser jdate_tanggal;
    private javax.swing.JTable tabel_stockrusak;
    private javax.swing.JTextField txtfield_product;
    private javax.swing.JTextField txtfield_satuan;
    private javax.swing.JTextField txtfield_stock;
    private javax.swing.JTextField txtfield_stockrusak;
    // End of variables declaration//GEN-END:variables
}
