/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Admin.View;

import Assets.DBConnection;
import java.sql.Connection;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JRDesignQuery;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Ryan F
 */
public class PilihReportStock extends javax.swing.JFrame {

    /**
     * Creates new form Test
     */
    public PilihReportStock() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btn_opname = new javax.swing.JButton();
        btn_pergerakan = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Pilih Report Stock");

        btn_opname.setText("Report Stock Opname");
        btn_opname.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_opnameMouseClicked(evt);
            }
        });
        btn_opname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_opnameActionPerformed(evt);
            }
        });

        btn_pergerakan.setText("Report Pergerakan Stock");
        btn_pergerakan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_pergerakanMouseClicked(evt);
            }
        });
        btn_pergerakan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pergerakanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(btn_opname)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(btn_pergerakan)
                .addGap(28, 28, 28))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(93, 93, 93))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_pergerakan, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_opname, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(53, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_opnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_opnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_opnameActionPerformed

    private void btn_pergerakanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pergerakanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_pergerakanActionPerformed

    private void btn_opnameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_opnameMouseClicked
      try {
        JasperDesign jd = JRXmlLoader.load("C:\\Users\\User\\Desktop\\JAVA_UAS_PBO\\UAS_OOP_POS\\src\\Admin_Report\\ReportStockProduct.jrxml");
        
        String sql = "SELECT \n" +
"    p.product_code,\n" +
"    p.product_name,\n" +
"    p.product_unit,\n" +
"    COALESCE(pb.total_purchase_qty, 0) AS purchase_qty,\n" +
"    COALESCE(sd.total_sale_qty, 0) AS sale_qty,\n" +
"    COALESCE(s.total_stok_rusak, 0) AS stok_rusak,  -- Perhatikan nama kolom di sini\n" +
"    COALESCE(pb.total_purchase_qty, 0) - COALESCE(sd.total_sale_qty, 0) - COALESCE(s.total_stok_rusak, 0) AS total\n" +
"FROM \n" +
"    product p\n" +
"LEFT JOIN (\n" +
"    SELECT id_product, SUM(purchase_qty) AS total_purchase_qty \n" +
"    FROM pembelian \n" +
"    GROUP BY id_product\n" +
") pb ON p.id_product = pb.id_product\n" +
"LEFT JOIN (\n" +
"    SELECT id_product, SUM(sale_qty) AS total_sale_qty \n" +
"    FROM sale_details \n" +
"    GROUP BY id_product\n" +
") sd ON p.id_product = sd.id_product \n" +
"LEFT JOIN (\n" +
"    SELECT id_product, SUM(stok_rusak) AS total_stok_rusak  -- Diperbaiki: total_stok_rusak (bukan total_stock_rusak)\n" +
"    FROM stock \n" +
"    GROUP BY id_product\n" +
") s ON p.id_product = s.id_product\n" +
"WHERE p.status = 'Y'\n" +
"ORDER BY p.product_code;";
         JRDesignQuery newQuery = new JRDesignQuery();
         newQuery.setText(sql);
         jd.setQuery(newQuery);
         
//         JOptionPane.showMessageDialog(null, "Test"); 
         JasperReport js = JasperCompileManager.compileReport(jd);
//         JOptionPane.showMessageDialog(null, "Test"); 
        // Koneksi database
        Connection conn = DBConnection.getConnection();
//        JOptionPane.showMessageDialog(null, "Connected!");

        JasperPrint jp = JasperFillManager.fillReport(js, null, conn);
        JasperViewer.viewReport(jp, false); // false = tidak exit aplikasi saat viewer ditutup
        this.dispose();
     } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Terjadi kesalahan saat membuka form tambah data.", "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btn_opnameMouseClicked

    private void btn_pergerakanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_pergerakanMouseClicked
      ReportProductStockView frame = new ReportProductStockView();
    frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE); // pakai JFrame
    frame.pack();
    frame.setLocationRelativeTo(null);
    frame.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_btn_pergerakanMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PilihReportStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PilihReportStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PilihReportStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PilihReportStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PilihReportStock().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_opname;
    private javax.swing.JButton btn_pergerakan;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
