/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Admin.View;
import Kasir.View.*;
import Assets.DBConnection;
import Admin.Controller.ProductCRUD;
import Admin.Model.Product;
import Kasir.Model.Sale;
import Kasir.Controller.HistoryController;
import Admin.Controller.TableStock;
import Admin.Controller.TableStockSearch;
import Admin.Model.PergerakanStock;
import Admin.Model.StockRusak;
import Kasir.Model.SaleDetail;
import javax.swing.table.DefaultTableModel;
import java.text.SimpleDateFormat;
import java.sql.*;
import java.util.ArrayList;
import javax.swing.*;
import java.awt.event.*;
import java.io.InputStream;
import java.text.NumberFormat;
import java.util.HashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.data.JRBeanCollectionDataSource;
import net.sf.jasperreports.engine.design.JRDesignQuery;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author user
 */
public class ReportProductStockView extends javax.swing.JFrame {
    private List<PergerakanStock> listPergerakanStock;
    /**
     * Creates new form ReportProduckStockView
     */
    public ReportProductStockView() {
        initComponents();
        setLocationRelativeTo(null);
        initCustomLogic();
    }
    
    private void initCustomLogic() {
        cb_filter.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Semua","Hari" ,"Bulan", "Tahun"}));

        // Default disable
        jcalender_month.setEnabled(false);
        jcalendar_year.setEnabled(false);
        jcalendar_day.setEnabled(false);

        cb_filter.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                String selected = (String) cb_filter.getSelectedItem();
                if ("Semua".equals(selected)) {
                    jcalender_month.setEnabled(false);
                    jcalendar_year.setEnabled(false);
                    jcalendar_day.setEnabled(false);
                } else if ("Bulan".equals(selected)) {
                    jcalender_month.setEnabled(true);
                    jcalendar_year.setEnabled(true);
                    jcalendar_day.setEnabled(false);
                } else if ("Tahun".equals(selected)) {
                    jcalender_month.setEnabled(false);
                    jcalendar_year.setEnabled(true);
                    jcalendar_day.setEnabled(false);
                }else if ("Hari".equals(selected)) {
                    jcalender_month.setEnabled(false);
                    jcalendar_year.setEnabled(false);
                    jcalendar_day.setEnabled(true);
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jcalendar_year = new com.toedter.calendar.JYearChooser();
        btn_cetakListStock = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        btn_cetakPenjualan = new javax.swing.JButton();
        jcalender_month = new com.toedter.calendar.JMonthChooser();
        jLabel5 = new javax.swing.JLabel();
        cb_filter = new javax.swing.JComboBox<>();
        jcalendar_day = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Tahun");

        btn_cetakListStock.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_cetakListStock.setText("Periksa List Stock");
        btn_cetakListStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cetakListStockActionPerformed(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("List Pembelian :");

        btn_cetakPenjualan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_cetakPenjualan.setText("Cetak Laporan Stock");
        btn_cetakPenjualan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_cetakPenjualanMouseClicked(evt);
            }
        });
        btn_cetakPenjualan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cetakPenjualanActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Tanggal");

        cb_filter.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Semua", "Hari", "Bulan", "Tahun" }));
        cb_filter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_filterActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Filter");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Bulan");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 782, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cb_filter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(49, 49, 49)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jcalendar_day, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jcalender_month, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jcalendar_year, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btn_cetakListStock)
                                .addGap(26, 26, 26)
                                .addComponent(btn_cetakPenjualan)))
                        .addGap(17, 17, 17))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cb_filter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1)
                        .addComponent(jLabel5))
                    .addComponent(jcalendar_year, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jcalendar_day, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jcalender_month, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_cetakListStock)
                    .addComponent(btn_cetakPenjualan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_cetakListStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cetakListStockActionPerformed
        String selectedFilter = (String) cb_filter.getSelectedItem();
        int month = jcalender_month.getMonth() + 1;
        int year = jcalendar_year.getYear();
        java.util.Date day = jcalendar_day.getDate();

        try {
            ProductCRUD controller = new ProductCRUD();
            this.listPergerakanStock = controller.getPergerakanStock(selectedFilter, day, month, year);

            // Siapkan model tabel untuk Laporan Pergerakan Stock
            DefaultTableModel model = new DefaultTableModel();
            model.addColumn("Tanggal");
            model.addColumn("Kode Produk");
            model.addColumn("Nama Produk");
            model.addColumn("Unit");
            model.addColumn("Jenis Transaksi");
            model.addColumn("Jumlah");
            
            jLabel4.setText("Detail Pergerakan Stok (" + selectedFilter + "):");

            if (listPergerakanStock.isEmpty()) {
                // Kosongkan tabel jika tidak ada data
                jTable2.setModel(model); 
                JOptionPane.showMessageDialog(this, "Tidak ada transaksi pada periode yang dipilih.");
            } else {
//                SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
                for (PergerakanStock ps : listPergerakanStock) {
                    model.addRow(new Object[]{
                        ps.getTanggal(),
                        ps.getProductCode(),
                        ps.getProductName(),
                        ps.getProductUnit(),
                        ps.getJenisTransaksi(),
                        ps.getJumlah()
                    });
                }
                jTable2.setModel(model);
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Gagal mengambil data laporan: " + e.getMessage());
            e.printStackTrace();
        }
    }//GEN-LAST:event_btn_cetakListStockActionPerformed
    
    private void loadReport() {
    String selectedFilter = (String) cb_filter.getSelectedItem();
    int month = jcalender_month.getMonth() + 1;
    int year = jcalendar_year.getYear();
    java.util.Date day = jcalendar_day.getDate();

    // Validasi input tanggal untuk filter "Hari"
    if ("Hari".equals(selectedFilter) && day == null) {
        JOptionPane.showMessageDialog(this, "Silakan pilih tanggal untuk filter 'Hari'.");
        return;
    }

    Map<String, Object> param = new HashMap<>();
    
    // <-- BAGIAN INI DIUBAH: Query dasar untuk pergerakan stok
    String baseQuery = "SELECT " +
        "   DATE_FORMAT(t.tanggal, '%e %M %Y') AS tanggal, " +
        "   p.product_code, p.product_name, p.product_unit, " +
        "   t.jenis_transaksi AS jenisTransaksi, t.jumlah " +
        "FROM product p JOIN (" +
        "   SELECT purchase_date AS tanggal, id_product, 'Stok Masuk' AS jenis_transaksi, purchase_qty AS jumlah FROM pembelian" +
        "   UNION ALL" +
        "   SELECT pj.sale_date AS tanggal, sd.id_product, 'Stok Keluar' AS jenis_transaksi, sd.sale_qty AS jumlah FROM sale_details sd JOIN penjualan pj ON sd.id_sale = pj.id_sale" +
        "   UNION ALL" +
        "   SELECT tanggal, id_product, 'Stok Rusak' AS jenis_transaksi, stok_rusak AS jumlah FROM stock" +
        ") AS t ON p.id_product = t.id_product WHERE p.status = 'Y' ";

    String dateFilterClause = "";

    // <-- BAGIAN INI DIUBAH: Klausa filter disesuaikan untuk query pergerakan stok
    switch (selectedFilter) {
        case "Hari":
            dateFilterClause = "AND DATE(t.tanggal) = $P{day} ";
            param.put("day", new java.sql.Date(day.getTime()));
            break;
        case "Bulan":
            dateFilterClause = "AND MONTH(t.tanggal) = $P{month} AND YEAR(t.tanggal) = $P{year} ";
            param.put("month", month);
            param.put("year", year);
            break;
        case "Tahun":
            dateFilterClause = "AND YEAR(t.tanggal) = $P{year} ";
            param.put("year", year);
            break;
        default: // "Semua"
            dateFilterClause = ""; // Tidak ada filter tanggal
            break;
    }

    // Gabungkan query menjadi satu string utuh
    String finalSql = baseQuery + dateFilterClause + "ORDER BY t.tanggal DESC";
    
    try {
        // Path ke file .jrxml Anda
        // Pastikan path ini benar atau gunakan metode classpath yang lebih aman
        JasperDesign jd = JRXmlLoader.load("C:\\Users\\User\\Desktop\\JAVA_UAS_PBO\\UAS_OOP_POS\\src\\Admin_Report\\Cetak_Laporan_PergerakanStock.jrxml");

        // Ganti query di dalam .jrxml dengan query yang baru kita buat
        JRDesignQuery newQuery = new JRDesignQuery();
        newQuery.setText(finalSql);
        jd.setQuery(newQuery);

        // Compile laporan
        JasperReport js = JasperCompileManager.compileReport(jd);

        // Dapatkan koneksi database
        Connection conn = DBConnection.getConnection();
        
        // Isi laporan dengan parameter dan koneksi, lalu tampilkan
        JasperPrint jp = JasperFillManager.fillReport(js, param, conn);
        JasperViewer.viewReport(jp, false);

    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Terjadi kesalahan saat membuka laporan: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
}
    
    private void btn_cetakPenjualanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_cetakPenjualanMouseClicked
        loadReport();
    }//GEN-LAST:event_btn_cetakPenjualanMouseClicked

    private void btn_cetakPenjualanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cetakPenjualanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_cetakPenjualanActionPerformed

    private void cb_filterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_filterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_filterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReportProductStockView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReportProductStockView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReportProductStockView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReportProductStockView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReportProductStockView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cetakListStock;
    private javax.swing.JButton btn_cetakPenjualan;
    private javax.swing.JComboBox<String> cb_filter;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private com.toedter.calendar.JDateChooser jcalendar_day;
    private com.toedter.calendar.JYearChooser jcalendar_year;
    private com.toedter.calendar.JMonthChooser jcalender_month;
    // End of variables declaration//GEN-END:variables
}
