/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Admin.View;
import Admin.Controller.SuppDAO;
import Admin.Model.Supp;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.util.ArrayList;
import java.util.List;
/**
 *
 * @author Ryan F
 */
public class Supplier extends javax.swing.JPanel {

    /**
     * Creates new form Supplier
     */
    
    private int selectedSuppId = -1;
     
    public Supplier() throws SQLException {
        initComponents();
       loadSupplierData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        main_supp = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        code_supp = new javax.swing.JTextField();
        name_supp = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        address_supp = new javax.swing.JTextField();
        add_supp = new javax.swing.JButton();
        upd_supp = new javax.swing.JButton();
        del_supp = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        contact_supp = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_supp = new javax.swing.JTable();
        clear_supp = new javax.swing.JButton();
        cBox_supp = new javax.swing.JComboBox<>();
        search_supp = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1270, 700));

        main_supp.setBackground(new java.awt.Color(0, 102, 102));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("SUPPLIER");

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Supplier Name :");

        code_supp.setBackground(new java.awt.Color(255, 255, 255));
        code_supp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                code_suppActionPerformed(evt);
            }
        });

        name_supp.setBackground(new java.awt.Color(255, 255, 255));
        name_supp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                name_suppActionPerformed(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Kode Supplier :");

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Address :");

        address_supp.setBackground(new java.awt.Color(255, 255, 255));
        address_supp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                address_suppActionPerformed(evt);
            }
        });

        add_supp.setBackground(new java.awt.Color(0, 153, 51));
        add_supp.setForeground(new java.awt.Color(255, 255, 255));
        add_supp.setText("Add");
        add_supp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_suppActionPerformed(evt);
            }
        });

        upd_supp.setBackground(new java.awt.Color(0, 102, 204));
        upd_supp.setForeground(new java.awt.Color(255, 255, 255));
        upd_supp.setText("Update");
        upd_supp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upd_suppActionPerformed(evt);
            }
        });

        del_supp.setBackground(new java.awt.Color(204, 0, 51));
        del_supp.setForeground(new java.awt.Color(255, 255, 255));
        del_supp.setText("Delete");
        del_supp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                del_suppActionPerformed(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Contact :");

        contact_supp.setBackground(new java.awt.Color(255, 255, 255));
        contact_supp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contact_suppActionPerformed(evt);
            }
        });

        table_supp.setBackground(new java.awt.Color(255, 255, 255));
        table_supp.setForeground(new java.awt.Color(0, 0, 0));
        table_supp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table_supp.setAlignmentX(0.0F);
        table_supp.setAlignmentY(0.0F);
        table_supp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_suppMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_supp);

        clear_supp.setBackground(new java.awt.Color(153, 153, 153));
        clear_supp.setForeground(new java.awt.Color(255, 255, 255));
        clear_supp.setText("Reset");
        clear_supp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear_suppActionPerformed(evt);
            }
        });

        cBox_supp.setBackground(new java.awt.Color(255, 255, 255));
        cBox_supp.setForeground(new java.awt.Color(0, 0, 0));
        cBox_supp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ID", "Kode Supplier", "Nama Supplier", "Contact", "Address" }));
        cBox_supp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cBox_suppActionPerformed(evt);
            }
        });

        search_supp.setBackground(new java.awt.Color(255, 255, 255));
        search_supp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                search_suppKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                search_suppKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                search_suppKeyTyped(evt);
            }
        });

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Search:");

        javax.swing.GroupLayout main_suppLayout = new javax.swing.GroupLayout(main_supp);
        main_supp.setLayout(main_suppLayout);
        main_suppLayout.setHorizontalGroup(
            main_suppLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(main_suppLayout.createSequentialGroup()
                .addGroup(main_suppLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(main_suppLayout.createSequentialGroup()
                        .addGroup(main_suppLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(main_suppLayout.createSequentialGroup()
                                .addGap(591, 591, 591)
                                .addComponent(jLabel1))
                            .addGroup(main_suppLayout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(main_suppLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2))
                                .addGap(18, 18, 18)
                                .addGroup(main_suppLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(code_supp, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(name_supp, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(59, 59, 59)
                                .addGroup(main_suppLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(main_suppLayout.createSequentialGroup()
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(contact_supp, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(main_suppLayout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(address_supp, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(165, 165, 165)
                        .addGroup(main_suppLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(main_suppLayout.createSequentialGroup()
                                .addComponent(search_supp, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(cBox_supp, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(main_suppLayout.createSequentialGroup()
                        .addGap(444, 444, 444)
                        .addComponent(add_supp, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(upd_supp, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(del_supp, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(clear_supp, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        main_suppLayout.setVerticalGroup(
            main_suppLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(main_suppLayout.createSequentialGroup()
                .addGroup(main_suppLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(main_suppLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, main_suppLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(main_suppLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(code_supp, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(contact_supp, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cBox_supp, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(search_supp, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(main_suppLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(name_supp, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(address_supp, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(26, 26, 26)
                .addGroup(main_suppLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(add_supp, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(upd_supp, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(del_supp, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clear_supp, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(main_supp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(main_supp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void code_suppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_code_suppActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_code_suppActionPerformed

    private void name_suppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_name_suppActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_name_suppActionPerformed

    private void address_suppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_address_suppActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_address_suppActionPerformed

    private void contact_suppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contact_suppActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contact_suppActionPerformed
    
    private void loadSupplierData() throws SQLException{
        SuppDAO suppDAO = new SuppDAO();
        List<Supp> suppliers = suppDAO.getSuppliers();
        String[][] data = new String[suppliers.size()][5];
        
        for(int i = 0; i < suppliers.size(); i++) {
        data[i][0] = String.valueOf(suppliers.get(i).getId());
        data[i][1] = suppliers.get(i).getCodeSupplier();
        data[i][2] = suppliers.get(i).getNameSupplier();
        data[i][3] = suppliers.get(i).getContactSupplier();
        data[i][4] = suppliers.get(i).getAddressSupplier();
    }
        String[] columnName = {"ID", "Kode Supplier", "Nama Supplier", "Contact", "Address"};
        table_supp.setModel(new javax.swing.table.DefaultTableModel(data, columnName));
    }
    
    private void clearForm() {
    code_supp.setText("");
    name_supp.setText("");
    contact_supp.setText("");
    address_supp.setText("");
    
    }
    
    private void add_suppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_suppActionPerformed
    String cd_sp = code_supp.getText();
    String nm_sp = name_supp.getText();
    String cn_sp = contact_supp.getText(); 
    String ad_sp = address_supp.getText();
    
    if(cd_sp.isEmpty() || nm_sp.isEmpty() || cn_sp.isEmpty() || ad_sp.isEmpty()){
        JOptionPane.showMessageDialog(this, "Please fill in all fields", "Input Error", JOptionPane.ERROR_MESSAGE);
    } else {
    
    Supp addSupp = new Supp(0,cd_sp, nm_sp, cn_sp, ad_sp);
    SuppDAO suppDAO;
    
    try {
    suppDAO = new SuppDAO();
    int res = suppDAO.insertSupplier(addSupp);
    if (res == 1) {
        JOptionPane.showMessageDialog(this, "Supplier created successfully ", "Success", JOptionPane.INFORMATION_MESSAGE);
        this.clearForm();
        loadSupplierData();
    } else {
        JOptionPane.showMessageDialog(this, "Error occurred while inserting ", "Error", JOptionPane.ERROR_MESSAGE);
    }
    } catch (SQLException ex){
        JOptionPane.showMessageDialog(this, "Error occurred while inserting", "Error", JOptionPane.ERROR_MESSAGE);
    }
    }
    }//GEN-LAST:event_add_suppActionPerformed

    private void clear_suppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear_suppActionPerformed
    clearForm();
    }//GEN-LAST:event_clear_suppActionPerformed

    private void upd_suppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upd_suppActionPerformed
    String cd_sp = code_supp.getText();
    String nm_sp = name_supp.getText();
    String cn_sp = contact_supp.getText(); 
    String ad_sp = address_supp.getText();
    
    if(cd_sp.isEmpty() || nm_sp.isEmpty() || cn_sp.isEmpty() || ad_sp.isEmpty()){
        JOptionPane.showMessageDialog(this, "Please fill in all fields", "Input Error", JOptionPane.ERROR_MESSAGE);
    } else {
      if(selectedSuppId != -1) {
          Supp updateSupp = new Supp(selectedSuppId, cd_sp, nm_sp, cn_sp, ad_sp);
          SuppDAO suppDAO;
          try {
    suppDAO = new SuppDAO();
    int res = suppDAO.updateSupplier(updateSupp);
    if (res == 1) {
        JOptionPane.showMessageDialog(this, "Supplier updated successfully ", "Success", JOptionPane.INFORMATION_MESSAGE);
        this.clearForm();
        loadSupplierData();
        selectedSuppId = -1;
    } else {
        JOptionPane.showMessageDialog(this, "Error occurred while updatting ", "Error", JOptionPane.ERROR_MESSAGE);
    }
    } catch (SQLException ex){
        JOptionPane.showMessageDialog(this, "Error occurred while updatting", "Error", JOptionPane.ERROR_MESSAGE);
    }
      } else {
          JOptionPane.showMessageDialog(this, "No Supplier Selected for update ", "Error", JOptionPane.ERROR_MESSAGE);
      }
    }
    }//GEN-LAST:event_upd_suppActionPerformed

    private void table_suppMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_suppMouseClicked
    int selectedRow = table_supp.getSelectedRow();
    if(selectedRow != -1){
        selectedSuppId = Integer.parseInt(table_supp.getValueAt(selectedRow, 0).toString());
        code_supp.setText(table_supp.getValueAt(selectedRow, 1).toString());
        name_supp.setText(table_supp.getValueAt(selectedRow, 2).toString());
        contact_supp.setText(table_supp.getValueAt(selectedRow, 3).toString());
        address_supp.setText(table_supp.getValueAt(selectedRow, 4).toString());
    }
    }//GEN-LAST:event_table_suppMouseClicked

    private void del_suppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_del_suppActionPerformed
   if(selectedSuppId != -1){
        int confirmation = JOptionPane.showConfirmDialog(this, "Are you sure you want to delete this Supplier?", "Confirm Deletion", JOptionPane.YES_NO_OPTION);
        if(confirmation == JOptionPane.YES_OPTION) {
        SuppDAO suppDAO;
         try {
         suppDAO = new SuppDAO();
         suppDAO.deleteSupplier(selectedSuppId);
         JOptionPane.showMessageDialog(this, "Supplier Deleted successfully ", "Success", JOptionPane.INFORMATION_MESSAGE);
         this.clearForm();
         loadSupplierData();
         selectedSuppId = -1;
         } catch (SQLException ex){
        JOptionPane.showMessageDialog(this, "Error occurred while deletting", "Error", JOptionPane.ERROR_MESSAGE);
    }
        }
   }else {
            JOptionPane.showMessageDialog(this, "No Supplier Selected for Delete ", "Error", JOptionPane.ERROR_MESSAGE);
       }
    }//GEN-LAST:event_del_suppActionPerformed

    private void search_suppKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_search_suppKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_search_suppKeyPressed

    private void search_suppKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_search_suppKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_search_suppKeyTyped

    private void search_suppKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_search_suppKeyReleased
    String sr_supp = search_supp.getText();
    String selectedColumn = cBox_supp.getSelectedItem().toString();
    String DBColumn = "";
    switch (selectedColumn) {
        case "ID":
            DBColumn = "id_supplier";
            break;
        case "Kode Supplier":
            DBColumn = "supp_code";
            break;
        case "Nama Supplier":
            DBColumn = "supp_name";
            break;
        case "Contact":
            DBColumn = "contact";
            break;
        case "Address":
            DBColumn = "address";
            break;
        default:
        DBColumn = "id_supplier";
    }
        try {
        if(sr_supp.isEmpty()) {
            loadSupplierData();
        } else {
        SuppDAO suppDAO = new SuppDAO();
        List<Supp> suppliers = suppDAO.searchSuppliers(sr_supp, DBColumn);
        
        String[][] data = new String[suppliers.size()][5];
        
        for(int i = 0; i < suppliers.size(); i++) {
        data[i][0] = String.valueOf(suppliers.get(i).getId());
        data[i][1] = suppliers.get(i).getCodeSupplier();
        data[i][2] = suppliers.get(i).getNameSupplier();
        data[i][3] = suppliers.get(i).getContactSupplier();
        data[i][4] = suppliers.get(i).getAddressSupplier();
    }
        String[] columnName = {"ID", "Kode Supplier", "Nama Supplier", "Contact", "Address"};
        table_supp.setModel(new javax.swing.table.DefaultTableModel(data, columnName));
    } }
    catch (SQLException ex){
        JOptionPane.showMessageDialog(this, "Error occurred while searching", "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_search_suppKeyReleased

    private void cBox_suppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cBox_suppActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cBox_suppActionPerformed
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_supp;
    private javax.swing.JTextField address_supp;
    private javax.swing.JComboBox<String> cBox_supp;
    private javax.swing.JButton clear_supp;
    private javax.swing.JTextField code_supp;
    private javax.swing.JTextField contact_supp;
    private javax.swing.JButton del_supp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel main_supp;
    private javax.swing.JTextField name_supp;
    private javax.swing.JTextField search_supp;
    private javax.swing.JTable table_supp;
    private javax.swing.JButton upd_supp;
    // End of variables declaration//GEN-END:variables
}
