/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package POS;
import backend_POS.Beli;
import backend_POS.BeliDAO;
import backend_POS.autoBox;
import backend_POS.comboBox;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
/**
 *
 * @author Ryan F
 */
public class Pembelian extends javax.swing.JPanel {

    /**
     * Creates new form Supplier
     */
    private int selectedPembelianId = -1;
     
    public Pembelian() throws SQLException {
        initComponents();
       loadPembelianData();
       loadComboBox(supp_pembelian, "Supplier");
       loadComboBox(product_pembelian, "Product");
       satuan_pembelian.setEditable(false);
       loadAutoBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        main_supp = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        satuan_pembelian = new javax.swing.JTextField();
        add_pembelian = new javax.swing.JButton();
        upd_pembelian = new javax.swing.JButton();
        del_pembelian = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_pembelian = new javax.swing.JTable();
        clear_pembelian = new javax.swing.JButton();
        cBox_pembelian = new javax.swing.JComboBox<>();
        search_pembelian = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jumlah_pembelian = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        product_pembelian = new javax.swing.JComboBox<>();
        supp_pembelian = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        harga_pembelian = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        table_supp1 = new javax.swing.JTable();
        date_pembelian = new com.toedter.calendar.JDateChooser();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1270, 700));

        main_supp.setBackground(new java.awt.Color(0, 102, 102));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("PEMBELIAN");

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Supplier :");

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Product :");

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Satuan :");

        satuan_pembelian.setBackground(new java.awt.Color(204, 204, 204));
        satuan_pembelian.setForeground(new java.awt.Color(0, 0, 0));
        satuan_pembelian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                satuan_pembelianActionPerformed(evt);
            }
        });
        satuan_pembelian.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                satuan_pembelianKeyTyped(evt);
            }
        });

        add_pembelian.setBackground(new java.awt.Color(0, 153, 51));
        add_pembelian.setForeground(new java.awt.Color(255, 255, 255));
        add_pembelian.setText("Add");
        add_pembelian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_pembelianActionPerformed(evt);
            }
        });

        upd_pembelian.setBackground(new java.awt.Color(0, 102, 204));
        upd_pembelian.setForeground(new java.awt.Color(255, 255, 255));
        upd_pembelian.setText("Update");
        upd_pembelian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upd_pembelianActionPerformed(evt);
            }
        });

        del_pembelian.setBackground(new java.awt.Color(204, 0, 51));
        del_pembelian.setForeground(new java.awt.Color(255, 255, 255));
        del_pembelian.setText("Delete");
        del_pembelian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                del_pembelianActionPerformed(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Date :");

        table_pembelian.setBackground(new java.awt.Color(255, 255, 255));
        table_pembelian.setForeground(new java.awt.Color(0, 0, 0));
        table_pembelian.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table_pembelian.setAlignmentX(0.0F);
        table_pembelian.setAlignmentY(0.0F);
        table_pembelian.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_pembelianMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_pembelian);

        clear_pembelian.setBackground(new java.awt.Color(153, 153, 153));
        clear_pembelian.setForeground(new java.awt.Color(255, 255, 255));
        clear_pembelian.setText("Reset");
        clear_pembelian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear_pembelianActionPerformed(evt);
            }
        });

        cBox_pembelian.setBackground(new java.awt.Color(255, 255, 255));
        cBox_pembelian.setForeground(new java.awt.Color(0, 0, 0));
        cBox_pembelian.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ID", "Nama Product", "Nama Supplier", "Tanggal Beli", "Jumlah Product", "Satuan", "Total Harga" }));
        cBox_pembelian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cBox_pembelianActionPerformed(evt);
            }
        });

        search_pembelian.setBackground(new java.awt.Color(255, 255, 255));
        search_pembelian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_pembelianActionPerformed(evt);
            }
        });
        search_pembelian.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                search_pembelianKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                search_pembelianKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                search_pembelianKeyTyped(evt);
            }
        });

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Search:");

        jumlah_pembelian.setBackground(new java.awt.Color(255, 255, 255));
        jumlah_pembelian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jumlah_pembelianActionPerformed(evt);
            }
        });

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Jumlah :");

        product_pembelian.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        product_pembelian.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                product_pembelianItemStateChanged(evt);
            }
        });

        supp_pembelian.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        supp_pembelian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supp_pembelianActionPerformed(evt);
            }
        });

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Total Harga :");

        harga_pembelian.setBackground(new java.awt.Color(255, 255, 255));
        harga_pembelian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                harga_pembelianActionPerformed(evt);
            }
        });
        harga_pembelian.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                harga_pembelianKeyTyped(evt);
            }
        });

        table_supp1.setBackground(new java.awt.Color(255, 255, 255));
        table_supp1.setForeground(new java.awt.Color(0, 0, 0));
        table_supp1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table_supp1.setAlignmentX(0.0F);
        table_supp1.setAlignmentY(0.0F);
        table_supp1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_supp1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(table_supp1);

        date_pembelian.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout main_suppLayout = new javax.swing.GroupLayout(main_supp);
        main_supp.setLayout(main_suppLayout);
        main_suppLayout.setHorizontalGroup(
            main_suppLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(main_suppLayout.createSequentialGroup()
                .addGap(591, 591, 591)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(main_suppLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(main_suppLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addGap(28, 28, 28)
                .addGroup(main_suppLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(supp_pembelian, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(product_pembelian, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addGroup(main_suppLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(main_suppLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(date_pembelian, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jumlah_pembelian, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addGroup(main_suppLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(main_suppLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(main_suppLayout.createSequentialGroup()
                        .addComponent(harga_pembelian, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(main_suppLayout.createSequentialGroup()
                        .addComponent(satuan_pembelian, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                        .addGroup(main_suppLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(main_suppLayout.createSequentialGroup()
                                .addComponent(search_pembelian, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cBox_pembelian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(57, 57, 57))))
            .addGroup(main_suppLayout.createSequentialGroup()
                .addGap(444, 444, 444)
                .addComponent(add_pembelian, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(upd_pembelian, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(del_pembelian, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(clear_pembelian, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        main_suppLayout.setVerticalGroup(
            main_suppLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(main_suppLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(main_suppLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(main_suppLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(main_suppLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(main_suppLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(main_suppLayout.createSequentialGroup()
                                    .addGroup(main_suppLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel3)
                                        .addComponent(product_pembelian, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel5))
                                    .addGap(18, 18, 18)
                                    .addGroup(main_suppLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel2)
                                        .addComponent(supp_pembelian, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(main_suppLayout.createSequentialGroup()
                                    .addComponent(date_pembelian, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGap(18, 18, 18)
                                    .addGroup(main_suppLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jumlah_pembelian, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel6))))
                            .addGroup(main_suppLayout.createSequentialGroup()
                                .addGroup(main_suppLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(satuan_pembelian, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(main_suppLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(harga_pembelian, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(main_suppLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(main_suppLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cBox_pembelian, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(search_pembelian, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(52, 52, 52)))
                .addGap(26, 26, 26)
                .addGroup(main_suppLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(add_pembelian, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(upd_pembelian, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(del_pembelian, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clear_pembelian, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(main_supp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(main_supp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void satuan_pembelianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_satuan_pembelianActionPerformed
   
    }//GEN-LAST:event_satuan_pembelianActionPerformed

    public void loadAutoBox (){
     try {
            BeliDAO beliDAO = new BeliDAO();
            String selectedProduct = ((String) product_pembelian.getSelectedItem());                       
            String satuan = beliDAO.getSatuanProduct(selectedProduct);
            if (satuan != null){
            satuan_pembelian.setText(satuan);
//            System.out.println("Satuan yang diatur: " + satuan); 
            }
            else {
            satuan_pembelian.setText("-");
//            System.out.println("Satuan tidak ditemukan untuk produk: " + selectedProduct);
            }
        } catch (SQLException ex) {
        System.out.println("Error");
        }
    }
        
    private void loadPembelianData() throws SQLException{
        BeliDAO suppDAO = new BeliDAO();
        List<Beli> beli = suppDAO.getBeli();
        String[][] data = new String[beli.size()][7];
        
        SimpleDateFormat dateFormat = new SimpleDateFormat("d MMMM yyyy");
        
        for(int i = 0; i < beli.size(); i++) {
        data[i][0] = String.valueOf(beli.get(i).getId());
        data[i][1] = beli.get(i).getProduct();
        data[i][2] = beli.get(i).getSupplier();
        
        Date tanggal = beli.get(i).getDate();
        data[i][3] = dateFormat.format(tanggal);
        
        data[i][4] = String.valueOf(beli.get(i).getQty());
        data[i][5] = beli.get(i).getUnit();
        data[i][6] = String.valueOf(beli.get(i).getTotalPrice());
    }
        String[] columnName = {"ID", "Nama Product", "Nama Supplier", "Tanggal Beli", "Jumlah Product", "Satuan", "Total Harga"};
        table_pembelian.setModel(new javax.swing.table.DefaultTableModel(data, columnName));
    }
    
    private void clearForm() {
    jumlah_pembelian.setText("");
    date_pembelian.setDate(null);
    harga_pembelian.setText("");
    }
    
    public void loadComboBox(JComboBox<String> comboBox, String name) throws SQLException{
        BeliDAO beliDAO = new BeliDAO();
        List<comboBox> comboBoxList = beliDAO.getComboBox(name);
        DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();
        for (comboBox item : comboBoxList) {
        model.addElement(item.getName()); 
    }
        comboBox.setModel(model);
    }
    
    
    private void add_pembelianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_pembelianActionPerformed
       String namaProduct = (String) product_pembelian.getSelectedItem();
       String namaSupplier = (String) supp_pembelian.getSelectedItem();
       Date tanggalPembelian = date_pembelian.getDate();
       String qtyPembelianStr = jumlah_pembelian.getText();
       String totalPembelianStr = harga_pembelian.getText();
       
       if(namaProduct.isEmpty() || namaSupplier.isEmpty() || tanggalPembelian == null || qtyPembelianStr.isEmpty() || totalPembelianStr.isEmpty()) {
           JOptionPane.showMessageDialog(this, "Please fill in all fields", "Input Error", JOptionPane.ERROR_MESSAGE);
       } else {
            int qtyPembelian = Integer.parseInt(qtyPembelianStr);
            float totalPembelian = Float.parseFloat(totalPembelianStr);
           
           Beli addBeli = new Beli(0, namaProduct, namaSupplier, tanggalPembelian, qtyPembelian, totalPembelian);
           BeliDAO beliDAO;
           try{
               beliDAO = new BeliDAO();
               int res = beliDAO.insertPembelian(addBeli);
               if (res == 1) {
               JOptionPane.showMessageDialog(this, "Pembelian created successfully ", "Success", JOptionPane.INFORMATION_MESSAGE);
               this.clearForm();
               loadPembelianData();
           } else {
               JOptionPane.showMessageDialog(this, "Error occurred while inserting ", "Error", JOptionPane.ERROR_MESSAGE);
               }
           
           }catch (SQLException ex){
        JOptionPane.showMessageDialog(this, "Error occurred while inserting", "Error", JOptionPane.ERROR_MESSAGE);
    }
       }  
       
       
    }//GEN-LAST:event_add_pembelianActionPerformed

    private void clear_pembelianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear_pembelianActionPerformed
    clearForm();
    }//GEN-LAST:event_clear_pembelianActionPerformed

    private void upd_pembelianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upd_pembelianActionPerformed
       String namaProduct = (String) product_pembelian.getSelectedItem();
       String namaSupplier = (String) supp_pembelian.getSelectedItem();
       Date tanggalPembelian = date_pembelian.getDate();
       String qtyPembelianStr = jumlah_pembelian.getText();
       String totalPembelianStr = harga_pembelian.getText();
       
       if(namaProduct.isEmpty() || namaSupplier.isEmpty() || tanggalPembelian == null || qtyPembelianStr.isEmpty() || totalPembelianStr.isEmpty()) {
           JOptionPane.showMessageDialog(this, "Please fill in all fields", "Input Error", JOptionPane.ERROR_MESSAGE);
       } else {
            int qtyPembelian = Integer.parseInt(qtyPembelianStr);
            float totalPembelian = Float.parseFloat(totalPembelianStr);
       if(selectedPembelianId != -1) {
           Beli updateBeli = new Beli(selectedPembelianId, namaProduct, namaSupplier, tanggalPembelian, qtyPembelian, totalPembelian);
           BeliDAO beliDAO;
           try {
               beliDAO = new BeliDAO();
           int res = beliDAO.updatePembelian(updateBeli);
           if (res == 1) {
           JOptionPane.showMessageDialog(this, "Pembelian updated successfully ", "Success", JOptionPane.INFORMATION_MESSAGE);
           this.clearForm();
           loadPembelianData();
           selectedPembelianId = -1;
    } else {
        JOptionPane.showMessageDialog(this, "Error occurred while updatting ", "Error", JOptionPane.ERROR_MESSAGE);
    }

           } catch (SQLException ex){
        JOptionPane.showMessageDialog(this, "Error occurred while updatting", "Error", JOptionPane.ERROR_MESSAGE);
    }
      } else {
          JOptionPane.showMessageDialog(this, "No Pembelian Selected for update ", "Error", JOptionPane.ERROR_MESSAGE);
      }
       }  
    }//GEN-LAST:event_upd_pembelianActionPerformed

    private void table_pembelianMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_pembelianMouseClicked
    int selectedRow = table_pembelian.getSelectedRow();
    if(selectedRow != -1){
        
        SimpleDateFormat dateFormat = new SimpleDateFormat("d MMMM yyyy"); 
        String dateString = table_pembelian.getValueAt(selectedRow, 3).toString();
        
        float hargaFloat = Float.parseFloat(table_pembelian.getValueAt(selectedRow, 6).toString());
        int hargaInteger = (int) hargaFloat; 
        
        selectedPembelianId = Integer.parseInt(table_pembelian.getValueAt(selectedRow, 0).toString());
        product_pembelian.setSelectedItem(table_pembelian.getValueAt(selectedRow, 1).toString());
        supp_pembelian.setSelectedItem(table_pembelian.getValueAt(selectedRow, 2).toString());
        try {
            date_pembelian.setDate(dateFormat.parse(dateString));
        } catch (ParseException ex) {
            System.out.println("Error Date!");
        }
        jumlah_pembelian.setText(table_pembelian.getValueAt(selectedRow, 4).toString());
        satuan_pembelian.setText(table_pembelian.getValueAt(selectedRow, 5).toString());
        harga_pembelian.setText(String.valueOf(hargaInteger));
    }  
    }//GEN-LAST:event_table_pembelianMouseClicked

    private void del_pembelianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_del_pembelianActionPerformed
   if(selectedPembelianId != -1){
        int confirmation = JOptionPane.showConfirmDialog(this, "Are you sure you want to delete this Supplier?", "Confirm Deletion", JOptionPane.YES_NO_OPTION);
        if(confirmation == JOptionPane.YES_OPTION) {
        BeliDAO beliDAO;
         try {
         beliDAO = new BeliDAO();
         beliDAO.deletePembelian(selectedPembelianId);
         JOptionPane.showMessageDialog(this, "Supplier Deleted successfully ", "Success", JOptionPane.INFORMATION_MESSAGE);
         this.clearForm();
         loadPembelianData();
         selectedPembelianId = -1;
         } catch (SQLException ex){
        JOptionPane.showMessageDialog(this, "Error occurred while deletting", "Error", JOptionPane.ERROR_MESSAGE);
    }
        }
   }else {
            JOptionPane.showMessageDialog(this, "No Supplier Selected for Delete ", "Error", JOptionPane.ERROR_MESSAGE);
       }
    }//GEN-LAST:event_del_pembelianActionPerformed

    private void search_pembelianKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_search_pembelianKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_search_pembelianKeyPressed

    private void search_pembelianKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_search_pembelianKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_search_pembelianKeyTyped

    private void search_pembelianKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_search_pembelianKeyReleased
      String sr_beli = search_pembelian.getText();
      String selectedColumn = cBox_pembelian.getSelectedItem().toString();
      String DBColumn = "";

      switch (selectedColumn) {
          case "ID" :
          DBColumn = "id_purchase";
          break;
          case "Nama Product" :
          DBColumn = "product_name";
          break;
          case "Nama Supplier" :
          DBColumn = "supp_name";
          break;
          case "Tanggal Beli" :
          DBColumn = "purchase_date";
          break;
          case "Jumlah Product" :
          DBColumn = "purchase_qty";
          break;
          case "Satuan" :
          DBColumn = "product_unit";
          break;
          case "Total Harga" :
          DBColumn = "total_price";
          break;
          default:
          DBColumn = "id_purchase";
      } try {
          if(sr_beli.isEmpty()) {
              loadPembelianData();
          } else {
            BeliDAO beliDAO = new BeliDAO();
            List<Beli> beli = beliDAO.searchPembelian(sr_beli, DBColumn);
        String[][] data = new String[beli.size()][7];
        
        SimpleDateFormat dateFormat = new SimpleDateFormat("d MMMM yyyy");
        
        for(int i = 0; i < beli.size(); i++) {
        data[i][0] = String.valueOf(beli.get(i).getId());
        data[i][1] = beli.get(i).getProduct();
        data[i][2] = beli.get(i).getSupplier();
        
        Date tanggal = beli.get(i).getDate();
        data[i][3] = dateFormat.format(tanggal);
        
        data[i][4] = String.valueOf(beli.get(i).getQty());
        data[i][5] = beli.get(i).getUnit();
        data[i][6] = String.valueOf(beli.get(i).getTotalPrice());
    }
        String[] columnName = {"ID", "Nama Product", "Nama Supplier", "Tanggal Beli", "Jumlah Product", "Satuan", "Total Harga"};
        table_pembelian.setModel(new javax.swing.table.DefaultTableModel(data, columnName)); 
          }
      } catch (SQLException ex){
        JOptionPane.showMessageDialog(this, "Error occurred while searching", "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_search_pembelianKeyReleased

    private void cBox_pembelianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cBox_pembelianActionPerformed
    String selectedColumn = cBox_pembelian.getSelectedItem().toString();
    if (selectedColumn == "Tanggal Beli"){
    search_pembelian.setText("YYYY-MM-DD");
    } else {
    search_pembelian.setText("");
    }
    }//GEN-LAST:event_cBox_pembelianActionPerformed

    private void jumlah_pembelianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jumlah_pembelianActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jumlah_pembelianActionPerformed

    private void supp_pembelianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supp_pembelianActionPerformed
     
    }//GEN-LAST:event_supp_pembelianActionPerformed

    private void harga_pembelianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_harga_pembelianActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_harga_pembelianActionPerformed

    private void satuan_pembelianKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_satuan_pembelianKeyTyped
    JOptionPane.showMessageDialog(null, "Tidak bisa mengedit field ini!");
    }//GEN-LAST:event_satuan_pembelianKeyTyped

    private void harga_pembelianKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_harga_pembelianKeyTyped
    
    }//GEN-LAST:event_harga_pembelianKeyTyped

    private void table_supp1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_supp1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_table_supp1MouseClicked

    private void product_pembelianItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_product_pembelianItemStateChanged
    if (evt.getStateChange() == java.awt.event.ItemEvent.SELECTED) {
        loadAutoBox();
    }
    }//GEN-LAST:event_product_pembelianItemStateChanged

    private void search_pembelianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_pembelianActionPerformed

    }//GEN-LAST:event_search_pembelianActionPerformed
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_pembelian;
    private javax.swing.JComboBox<String> cBox_pembelian;
    private javax.swing.JButton clear_pembelian;
    private com.toedter.calendar.JDateChooser date_pembelian;
    private javax.swing.JButton del_pembelian;
    private javax.swing.JTextField harga_pembelian;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jumlah_pembelian;
    private javax.swing.JPanel main_supp;
    private javax.swing.JComboBox<String> product_pembelian;
    private javax.swing.JTextField satuan_pembelian;
    private javax.swing.JTextField search_pembelian;
    private javax.swing.JComboBox<String> supp_pembelian;
    private javax.swing.JTable table_pembelian;
    private javax.swing.JTable table_supp1;
    private javax.swing.JButton upd_pembelian;
    // End of variables declaration//GEN-END:variables
}
